### ISSUE TITLE
Getting Empty DataFrame/CSV file from experiment

### ISSUE THREAD

**Issue by avacecil** [bihealth/NeatMS#3]
Hi,
I've been trying to export the experiment to a dataframe / csv file from the sample data provided and I keep getting an empty dataframe and / or file. I am able to see peaks and interrogate the data in other ways, but for some reason it won't give me any data when I try to export. Any ideas? Here is my code if that helps:

import NeatMS as ntms
raw_data_folder_path = 'C:/Test/mzML'
feature_table_path = 'C:/Test/aligned_features.csv'
input_data = 'mzmine'
experiment = ntms.Experiment(raw_data_folder_path, feature_table_path, input_data)
my_dataframe = experiment.export_to_dataframe()
print(my_dataframe)

**Comment by yoglo** [comment]
The export function only allows exporting peaks once they have been labelled, so you will need to load/train and run a model first before exporting (see https://neatms.readthedocs.io/en/latest/first-steps/basic-usage/#load-a-neural-network-model).

If you want to export the data before labelling peaks you will need to write the code for it, no function currently exists for that purpose (the exported data will be the same as the input data though). 

Does that answer your question?

**Comment by avacecil** [comment]
Yes, thank you!
