### ISSUE TITLE
Number of peaks per sample in NeatMS experiment does not match 

### ISSUE THREAD

**Issue by margotbligh** [bihealth/NeatMS#7]
Hello,

I am following the tutorial of NeatMS for basic usage.

I have an experiment with 28 files that I have processed (peak picking, retention time adjustment based on subset, peak grouping, peak filling) in R with XCMS (version 3.16.1). I created the feature table as per the documentation and successfully created a NeatMS experiment. 

However I do not understand the numbers of peaks that are returned when I run this code:

`for sample in experiment.samples:
    print('Sample {} : {} peaks'.format(sample.name,len(sample.feature_list)))`

I will focus on one sample as an example (sample number 1, name = 03_MS31_20221004_stdmix_03.mzML).

I get the following from the code above for this sample:

`Sample 03_MS31_20221004_stdmix_03 : 7039 peaks `

However, according to the XCMS object ("res") in R and the feature_dataframe generated from it this sample should have 7638 peaks :

```
> feature_dataframe %>% filter(sample == 1) %>% nrow()
[1] 7638
>feature_dataframe %>% filter(sample_name == "03_MS31_20221004_stdmix_03.mzML") %>% nrow()
[1] 7638
> chromPeakData(filterFile(res, 1)) %>% nrow()
[1] 7638
```

The peak number before filling is 3261

```
> feature_dataframe <- as.data.frame(chromPeaks(dropAdjustedRtime(res)))
> feature_dataframe %>% filter(sample == 1) %>% nrow()
[1] 3261
```

Can you please help me understand where the number 7039 peaks is coming from?

**Comment by yoglo** [comment]
Hello Margot,

The difference comes from the fact that XCMS sometimes assigns several peaks from single samples to the same feature (this happens during grouping). 

The code
`for sample in experiment.samples: print('Sample {} : {} peaks'.format(sample.name,len(sample.feature_list)))`
returns the number of features per sample, so any peaks belonging to the same feature are aggregated and counted as one. 

To access the total number of peaks, you can replace `sample.feature_list` with `sample.peak_list`. This should return the same number as XCMS.

I hope this helps.

**Comment by margotbligh** [comment]
Hi Yoan,

Thanks for the quick reply, this worked :) I did think this, but when I checked the number of unique features for that sample in R I got the number 6725 features, so I still don't understand where the number 7039 comes from?

```
> feature_dataframe %>% 
+   filter(sample_name == "03_MS31_20221004_stdmix_03.mzML") %>% 
+   select(feature_id) %>% 
+   distinct() %>% nrow()
[1] 6725
```

**Comment by yoglo** [comment]
Can you check in the dataframe that you export from XCMS if there are peaks with no associated features?

In NeatMS, the data structure is built in a way that every peak is associated to a feature (even if a feature contains only one peak from one sample). So if you add the number of features reported by XCMS to the number of orphan peaks (peaks with no associated features), it should add up to the number of features returned by NeatMS.

Hopefully you get the right number, if not let me know and I'll be happy to take a look at the feature table to help solve this.

**Comment by margotbligh** [comment]
Ok yes so there are 315 peaks that have no ID assigned for that sample:

```
> 
[1] 315
```
So number of unique features (6725) + number of peaks with no feature (315) = 7,040. This is exactly one less than the number of features reported for the NeatMS experiment object. Any idea where the one missing feature could come from?

Here is a link to the dataframe (it is too large to upload here): https://owncloud.mpi-bremen.de/index.php/s/ccspBc9dGZ9k8cV

Thanks for much helping me understand also :)

**Comment by yoglo** [comment]
Sorry for the delay. I am not sure where this difference is coming from, I will look into the dataframe and get back to you shortly.

**Comment by yoglo** [comment]
As far as I can see, NeatMS seems to load the correct number of features/peaks from the dataframe you have exported (see code below). There are 6724 unique features (containing several peaks) and 315 peaks with no feature ID assigned. 

```python
df = pd.read_csv("aligned_feature_table.csv")
df[(df["sample_name"] == "03_MS31_20221004_stdmix_03.mzML") & (df["feature_id"].notnull())]["feature_id"].unique().size
6724
df[(df["sample_name"] == "03_MS31_20221004_stdmix_03.mzML") & (df["feature_id"].isnull())]["peak_id"].unique().size
315
```

I believe the difference comes from the fact that in your R code, the entries with NA in the feature_id column are counted as one entry. Adding a filter to exclude NAs should give you the correct number. 

```R
feature_dataframe %>% 
+   filter(sample_name == "03_MS31_20221004_stdmix_03.mzML") %>% 
+   filter(!is.na(feature_id)) %>% 
+   select(feature_id) %>% 
+   distinct() %>% nrow()
```
I hope that fixes the issue.

**Comment by margotbligh** [comment]
Yes perfect thank you!
